### ISSUE TITLE
Feature Request: M5Atom Support

### ISSUE THREAD

**Issue by nkrick** [m5stack/M5Stack-platformio#1]
What would it take to get M5Atom/M5Atom Lite support added to platformio?  I'd like to use ESPHome to compile firmware for M5Atoms to use with Home Assistant. ESPHome uses PlatformIO and PlatformIO links back to git-hub repos for the various devices that are supported, so it appears that support has to start here?  Please let me know if I am looking in the wrong place to get M5Atom support for PlatformIO.

**Comment by TimDeve** [comment]
For people like me who ended up here looking for how to use platformio with the atom, looking at the [M5 docs](https://docs.m5stack.com/#/en/core/atom_matrix)  you can see that the Arduino IDE board is the same as the M5Stick.

This example config works:
```ino
[env:atom]
platform = espressif32
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200

lib_deps =
  M5Atom@0.0.1
  FastLED@3.3.3
```

**Comment by Zontex** [comment]
Hello, we opened a new topic for "wish list" in forum.m5stack.com feel free to ask your wish over there and we will push it forward :)
